version: '3'
services:
    php:
        build: ./php/
        volumes:
            - ./code/language:/var/www/html
            - ./php/log/php_log:/var/log/php_log:rw
        links:
            - postgres
            - redis
        environment:
            XDEBUG_CONFIG: "remote_host=10.254.254.254 idekey=languageDocker remote_enable=1 remote_handler=dbgp remote_port=9000 remote_autostart=1 remote_connect_back=0 remote_log=/var/log/php_log/xdebug.log"
            PHP_IDE_CONFIG: "serverName=language.develop.com"
        restart: always
    postgres:
        build: ./postgres/
        environment:
          - POSTGRES_PASSWORD=U2F77NbTyytwoCUVkpFmDs7TJDCkUnrPUMspDanAM2ywEFuZPszYEuwLyEvrvnJr
          - POSTGRES_USER=language-manager-postgres
          - POSTGRES_DB=language
        ports:
          - 5433:5432
        restart: always
    nginx:
        build: ./nginx/
        volumes:
            - ./nginx/log:/var/log/nginx:rw
        links:
            - php:php
        ports:
            - 8888:80
        restart: always
    redis:
        build: ./redis/
        ports:
          - 7369:6379
        restart: always
